require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MercadoPagoClientsController do

  # This should return the minimal set of attributes required to create a valid
  # MercadoPagoClient. As you add validations to MercadoPagoClient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "proyect_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MercadoPagoClientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mercado_pago_clients as @mercado_pago_clients" do
      mercado_pago_client = MercadoPagoClient.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mercado_pago_clients).should eq([mercado_pago_client])
    end
  end

  describe "GET show" do
    it "assigns the requested mercado_pago_client as @mercado_pago_client" do
      mercado_pago_client = MercadoPagoClient.create! valid_attributes
      get :show, {:id => mercado_pago_client.to_param}, valid_session
      assigns(:mercado_pago_client).should eq(mercado_pago_client)
    end
  end

  describe "GET new" do
    it "assigns a new mercado_pago_client as @mercado_pago_client" do
      get :new, {}, valid_session
      assigns(:mercado_pago_client).should be_a_new(MercadoPagoClient)
    end
  end

  describe "GET edit" do
    it "assigns the requested mercado_pago_client as @mercado_pago_client" do
      mercado_pago_client = MercadoPagoClient.create! valid_attributes
      get :edit, {:id => mercado_pago_client.to_param}, valid_session
      assigns(:mercado_pago_client).should eq(mercado_pago_client)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MercadoPagoClient" do
        expect {
          post :create, {:mercado_pago_client => valid_attributes}, valid_session
        }.to change(MercadoPagoClient, :count).by(1)
      end

      it "assigns a newly created mercado_pago_client as @mercado_pago_client" do
        post :create, {:mercado_pago_client => valid_attributes}, valid_session
        assigns(:mercado_pago_client).should be_a(MercadoPagoClient)
        assigns(:mercado_pago_client).should be_persisted
      end

      it "redirects to the created mercado_pago_client" do
        post :create, {:mercado_pago_client => valid_attributes}, valid_session
        response.should redirect_to(MercadoPagoClient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mercado_pago_client as @mercado_pago_client" do
        # Trigger the behavior that occurs when invalid params are submitted
        MercadoPagoClient.any_instance.stub(:save).and_return(false)
        post :create, {:mercado_pago_client => { "proyect_id" => "invalid value" }}, valid_session
        assigns(:mercado_pago_client).should be_a_new(MercadoPagoClient)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MercadoPagoClient.any_instance.stub(:save).and_return(false)
        post :create, {:mercado_pago_client => { "proyect_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mercado_pago_client" do
        mercado_pago_client = MercadoPagoClient.create! valid_attributes
        # Assuming there are no other mercado_pago_clients in the database, this
        # specifies that the MercadoPagoClient created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MercadoPagoClient.any_instance.should_receive(:update).with({ "proyect_id" => "1" })
        put :update, {:id => mercado_pago_client.to_param, :mercado_pago_client => { "proyect_id" => "1" }}, valid_session
      end

      it "assigns the requested mercado_pago_client as @mercado_pago_client" do
        mercado_pago_client = MercadoPagoClient.create! valid_attributes
        put :update, {:id => mercado_pago_client.to_param, :mercado_pago_client => valid_attributes}, valid_session
        assigns(:mercado_pago_client).should eq(mercado_pago_client)
      end

      it "redirects to the mercado_pago_client" do
        mercado_pago_client = MercadoPagoClient.create! valid_attributes
        put :update, {:id => mercado_pago_client.to_param, :mercado_pago_client => valid_attributes}, valid_session
        response.should redirect_to(mercado_pago_client)
      end
    end

    describe "with invalid params" do
      it "assigns the mercado_pago_client as @mercado_pago_client" do
        mercado_pago_client = MercadoPagoClient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MercadoPagoClient.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercado_pago_client.to_param, :mercado_pago_client => { "proyect_id" => "invalid value" }}, valid_session
        assigns(:mercado_pago_client).should eq(mercado_pago_client)
      end

      it "re-renders the 'edit' template" do
        mercado_pago_client = MercadoPagoClient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MercadoPagoClient.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercado_pago_client.to_param, :mercado_pago_client => { "proyect_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mercado_pago_client" do
      mercado_pago_client = MercadoPagoClient.create! valid_attributes
      expect {
        delete :destroy, {:id => mercado_pago_client.to_param}, valid_session
      }.to change(MercadoPagoClient, :count).by(-1)
    end

    it "redirects to the mercado_pago_clients list" do
      mercado_pago_client = MercadoPagoClient.create! valid_attributes
      delete :destroy, {:id => mercado_pago_client.to_param}, valid_session
      response.should redirect_to(mercado_pago_clients_url)
    end
  end

end
